# Generated by Django 3.0.8 on 2020-07-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20200720_1930'),
        ('persona', '0002_habilidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Mi empleado', 'verbose_name_plural': 'Empleados de la Empresa'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='persona.habilidad'),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'departamento')},
        ),
    ]
